name: repetition_counter
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.35.0

dependencies:
  camera: ^0.11.3
  clock: ^1.1.2
  collection: ^1.19.1
  flutter: { sdk: flutter }
  flutter_mediapipe_vision: ^0.2.1
  meta: ^1.17.0

dev_dependencies:
  fake_async: ^1.3.3
  test: ^1.28.0
  total_lints: ^3.10.0
